# Generated by Django 4.0.4 on 2022-05-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('seniorty_level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior', 'Junior'), ('Associate', 'Associate'), ('Mid Senior Level', 'Mid Senior Level'), ('Senior', 'Senior'), ('Lead', 'Lead')], max_length=200)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=200)),
                ('description', models.TextField()),
                ('experince', models.TextField()),
                ('salary', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('resume', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='candidates',
            field=models.ManyToManyField(related_name='job_candidates', to='main.jobseeker'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
