# Generated by Django 4.0.4 on 2022-05-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_savedjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='experince',
            new_name='Required_experince',
        ),
    ]
